// first element is key, second element is value (in list)
const RandEnchant = new Map<string, string>([
    ["-15", "of Spirit"],
    ["-16", "of Stamina"],
    ["-17", "of Strength"],
    ["-18", "of Agility"],
    ["-19", "of Intellect"],
    ["-20", "of Power"],
    ["-21", "of Arcane Wrath"],
    ["-22", "of Fiery Wrath"],
    ["-23", "of Frozen Wrath"],
    ["-24", "of Nature's Wrath"],
    ["-25", "of Shadow Wrath"],
    ["-26", "of Intellect"],
    ["-27", "of Nimbleness"],
    ["-28", "of Stamina"],
    ["-30", "of Spirit"],
    ["-61", "of Intellect"],
    ["-62", "of Strength"],
    ["-63", "of Agility"],
    ["-64", "of Power"],
    ["-65", "of Magic"],
    ["-84", "of Stamina"],
    ["-99", "of Speed"],
    ["-5", "of the Monkey"],
    ["-6", "of the Eagle"],
    ["-7", "of the Bear"],
    ["-8", "of the Whale"],
    ["-9", "of the Owl"],
    ["-10", "of the Gorilla"],
    ["-11", "of the Falcon"],
    ["-12", "of the Boar"],
    ["-13", "of the Wolf"],
    ["-14", "of the Tiger"],
    ["-29", "of Eluding"],
    ["-31", "of Arcane Protection"],
    ["-32", "of Fire Protection"],
    ["-33", "of Frost Protection"],
    ["-34", "of Nature Protection"],
    ["-35", "of Shadow Protection"],
    ["-47", "of Blocking"],
    ["-68", "of the Bear"],
    ["-69", "of the Eagle"],
    ["-78", "of the Monkey"],
    ["-81", "of the Whale"],
    ["-140", "of the Wraith"],
    ["-141", "of the Wind"],
    ["-142", "of the Master"],
    ["-144", "of the Shark"],
    ["-145", "of the Panther"],
    ["-146", "Crit/Mastery"],
    ["-147", "of the Shark"],
    ["-148", "Crit/Spirit"],
    ["-150", "of the Panther"],
    ["-151", "of the Wind"],
    ["-152", "of the Master"],
    ["-153", "of the Wraith"],
    ["-154", "of the Shark"],
    ["-156", "of the Wraith"],
    ["-157", "of the Panther"],
    ["-158", "of the Wind"],
    ["-159", "of the Master"],
    ["-160", "of the Mongoose"],
    ["-161", "of Storms"],
    ["-162", "of Flames"],
    ["-163", "of the Mongoose"],
    ["-164", "of Storms"],
    ["-165", "of Flames"],
    ["-166", "of the Mongoose"],
    ["-167", "of Storms"],
    ["-168", "of Flames"],
    ["-36", "of the Sorcerer"],
    ["-37", "of the Seer"],
    ["-38", "of the Prophet"],
    ["-39", "of the Invoker"],
    ["-40", "of the Bandit"],
    ["-41", "of the Beast"],
    ["-42", "of the Elder"],
    ["-43", "of the Soldier"],
    ["-44", "of the Elder"],
    ["-45", "of the Champion"],
    ["-46", "of the Test"],
    ["-48", "of Paladin Testing"],
    ["-49", "of the Grove"],
    ["-50", "of the Hunt"],
    ["-51", "of the Mind"],
    ["-52", "of the Crusade"],
    ["-53", "of the Vision"],
    ["-54", "of the Ancestor"],
    ["-55", "of the Nightmare"],
    ["-56", "of the Battle"],
    ["-57", "of the Shadow"],
    ["-58", "of the Sun"],
    ["-59", "of the Moon"],
    ["-60", "of the Wild"],
    ["-66", "of the Knight"],
    ["-67", "of the Seer"],
    ["-70", "of the Ancestor"],
    ["-71", "of the Bandit"],
    ["-72", "of the Battle"],
    ["-73", "of the Elder"],
    ["-74", "of the Beast"],
    ["-75", "of the Champion"],
    ["-76", "of the Grove"],
    ["-77", "of the Knight"],
    ["-79", "of the Moon"],
    ["-80", "of the Wild"],
    ["-82", "of the Vision"],
    ["-83", "of the Sun"],
    ["-85", "of the Sorcerer"],
    ["-86", "of the Soldier"],
    ["-87", "of the Shadow"],
    ["-88", "of the Foreseer"],
    ["-89", "of the Thief"],
    ["-90", "of the Necromancer"],
    ["-91", "of the Marksman"],
    ["-92", "of the Squire"],
    ["-93", "of Restoration"],
    ["-139", "of the Mercenary"],
    ["-100", "of the Principle"],
    ["-101", "of the Sentinel"],
    ["-102", "of the Hero"],
    ["-103", "of the Avatar"],
    ["-104", "of the Embodiment"],
    ["-105", "of the Guardian"],
    ["-106", "of the Defender"],
    ["-107", "of the Exemplar"],
    ["-108", "of the Curator"],
    ["-109", "of the Preserver"],
    ["-110", "of the Elements"],
    ["-111", "of the Paradigm"],
    ["-112", "of the Pattern"],
    ["-113", "of the Essence"],
    ["-114", "of the Flameblaze"],
    ["-115", "of the Archetype"],
    ["-116", "of the Manifestation"],
    ["-117", "of the Incarnation"],
    ["-118", "of the Faultline"],
    ["-119", "of the Ideal"],
    ["-120", "of the Earthshaker"],
    ["-121", "of the Landslide"],
    ["-122", "of the Earthfall"],
    ["-123", "of the Earthbreaker"],
    ["-124", "of the Mountainbed"],
    ["-125", "of the Bedrock"],
    ["-126", "of the Substratum"],
    ["-127", "of the Bouldercrag"],
    ["-128", "of the Rockslab"],
    ["-129", "of the Wildfire"],
    ["-130", "of the Fireflash"],
    ["-131", "of the Undertow"],
    ["-132", "of the Wavecrest"],
    ["-133", "of the Stormblast"],
    ["-134", "of the Galeburst"],
    ["-135", "of the Windflurry"],
    ["-136", "of the Zephyr"],
    ["-137", "of the Windstorm"],
    ["-138", "of the Feverflare"],
    ["-143", "of the Scorpion"],
    ["-149", "of the Scorpion"],
    ["-155", "of the Scorpion"],
    ["-344", "of the Decimator"],
    ["-345", "of the Unerring"],
    ["-346", "of the Adroit"],
    ["-347", "of the Savant"],
    ["-348", "of the Impatient"],
    ["-349", "of the Bladewall"],
    ["-350", "of the Untouchable"],
    ["-351", "of the Pious"],
    ["-352", "of the Landslide"],
    ["-353", "of the Stormblast"],
    ["-354", "of the Galeburst"],
    ["-355", "of the Windflurry"],
    ["-356", "of the Windstorm"],
    ["-357", "of the Zephyr"],
    ["-359", "of the Flameblaze"],
    ["-360", "of the Fireflash"],
    ["-361", "of the Feverflare"],
    ["-362", "of the Undertow"],
    ["-363", "of the Wavecrest"],
    ["-364", "of the Earthbreaker"],
    ["-365", "of the Faultline"],
    ["-366", "of the Mountainbed"],
    ["-367", "of the Bedrock"],
    ["-368", "of the Bouldercrag"],
    ["-369", "of the Rockslab"],
    ["-370", "of the Earthshaker"],
    ["-371", "of the Earthfall"]
]);
export { RandEnchant };
