using ArgentPonyWarcraftClient;

public interface IWarcraftRedisProxy
{
    Task<PvpLeaderboard> GetShuffleWarriorFuryLeaderboard(string region);
    Task<PvpLeaderboard> GetShuffleDeathKnightBloodLeaderboard(string region);
    Task<PvpLeaderboard> GetShuffleDeathKnightFrostLeaderboard(string region);
    Task<PvpLeaderboard> GetShuffleDeathKnightUnholyLeaderboard(string region);
    Task<PvpLeaderboard> GetShuffleDemonHunterDevourerLeaderboard(string region);
    Task<PvpLeaderboard> GetShuffleDemonHunterHavocLeaderboard(string region);
    Task<PvpLeaderboard> GetShuffleDemonHunterVengeanceLeaderboard(string region);
    Task<PvpLeaderboard> GetShuffleDruidBalanceLeaderboard(string region);
    Task<PvpLeaderboard> GetShuffleDruidFeralLeaderboard(string region);
    Task<PvpLeaderboard> GetShuffleDruidGuardianLeaderboard(string region);
    Task<PvpLeaderboard> GetShuffleDruidRestorationLeaderboard(string region);
    Task<PvpLeaderboard> GetShuffleEvokerDevastationLeaderboard(string region);
    Task<PvpLeaderboard> GetShuffleEvokerPreservationLeaderboard(string region);
    Task<PvpLeaderboard> GetShuffleEvokerAugmentationLeaderboard(string region);
    Task<PvpLeaderboard> GetShuffleHunterBeastMasteryLeaderboard(string region);
    Task<PvpLeaderboard> GetShuffleHunterMarksmanshipLeaderboard(string region);
    Task<PvpLeaderboard> GetShuffleHunterSurvivalLeaderboard(string region);
    Task<PvpLeaderboard> GetShuffleMageArcaneLeaderboard(string region);
    Task<PvpLeaderboard> GetShuffleMageFireLeaderboard(string region);
    Task<PvpLeaderboard> GetShuffleMageFrostLeaderboard(string region);
    Task<PvpLeaderboard> GetShuffleMonkBrewmasterLeaderboard(string region);
    Task<PvpLeaderboard> GetShuffleMonkWindwalkerLeaderboard(string region);
    Task<PvpLeaderboard> GetShuffleMonkMistweaverLeaderboard(string region);
    Task<PvpLeaderboard> GetShufflePaladinHolyLeaderboard(string region);
    Task<PvpLeaderboard> GetShufflePaladinProtectionLeaderboard(string region);
    Task<PvpLeaderboard> GetShufflePaladinRetributionLeaderboard(string region);
    Task<PvpLeaderboard> GetShufflePriestDisciplineLeaderboard(string region);
    Task<PvpLeaderboard> GetShufflePriestHolyLeaderboard(string region);
    Task<PvpLeaderboard> GetShufflePriestShadowLeaderboard(string region);
    Task<PvpLeaderboard> GetShuffleRogueAssassinationLeaderboard(string region);
    Task<PvpLeaderboard> GetShuffleRogueOutlawLeaderboard(string region);
    Task<PvpLeaderboard> GetShuffleRogueSubtletyLeaderboard(string region);
    Task<PvpLeaderboard> GetShuffleShamanElementalLeaderboard(string region);
    Task<PvpLeaderboard> GetShuffleShamanEnhancementLeaderboard(string region);
    Task<PvpLeaderboard> GetShuffleShamanRestorationLeaderboard(string region);
    Task<PvpLeaderboard> GetShuffleWarlockAfflictionLeaderboard(string region);
    Task<PvpLeaderboard> GetShuffleWarlockDemonologyLeaderboard(string region);
    Task<PvpLeaderboard> GetShuffleWarlockDestructionLeaderboard(string region);
    Task<PvpLeaderboard> GetShuffleWarriorArmsLeaderboard(string region);
    Task<PvpLeaderboard> GetShuffleWarriorProtectionLeaderboard(string region);
    Task<PvpLeaderboard> GetBlitzWarriorFuryLeaderboard(string region);
    Task<PvpLeaderboard> GetBlitzDeathKnightBloodLeaderboard(string region);
    Task<PvpLeaderboard> GetBlitzDeathKnightFrostLeaderboard(string region);
    Task<PvpLeaderboard> GetBlitzDeathKnightUnholyLeaderboard(string region);
    Task<PvpLeaderboard> GetBlitzDemonHunterDevourerLeaderboard(string region);
    Task<PvpLeaderboard> GetBlitzDemonHunterHavocLeaderboard(string region);
    Task<PvpLeaderboard> GetBlitzDemonHunterVengeanceLeaderboard(string region);
    Task<PvpLeaderboard> GetBlitzDruidBalanceLeaderboard(string region);
    Task<PvpLeaderboard> GetBlitzDruidFeralLeaderboard(string region);
    Task<PvpLeaderboard> GetBlitzDruidGuardianLeaderboard(string region);
    Task<PvpLeaderboard> GetBlitzDruidRestorationLeaderboard(string region);
    Task<PvpLeaderboard> GetBlitzEvokerDevastationLeaderboard(string region);
    Task<PvpLeaderboard> GetBlitzEvokerPreservationLeaderboard(string region);
    Task<PvpLeaderboard> GetBlitzEvokerAugmentationLeaderboard(string region);
    Task<PvpLeaderboard> GetBlitzHunterBeastMasteryLeaderboard(string region);
    Task<PvpLeaderboard> GetBlitzHunterMarksmanshipLeaderboard(string region);
    Task<PvpLeaderboard> GetBlitzHunterSurvivalLeaderboard(string region);
    Task<PvpLeaderboard> GetBlitzMageArcaneLeaderboard(string region);
    Task<PvpLeaderboard> GetBlitzMageFireLeaderboard(string region);
    Task<PvpLeaderboard> GetBlitzMageFrostLeaderboard(string region);
    Task<PvpLeaderboard> GetBlitzMonkBrewmasterLeaderboard(string region);
    Task<PvpLeaderboard> GetBlitzMonkWindwalkerLeaderboard(string region);
    Task<PvpLeaderboard> GetBlitzMonkMistweaverLeaderboard(string region);
    Task<PvpLeaderboard> GetBlitzPaladinHolyLeaderboard(string region);
    Task<PvpLeaderboard> GetBlitzPaladinProtectionLeaderboard(string region);
    Task<PvpLeaderboard> GetBlitzPaladinRetributionLeaderboard(string region);
    Task<PvpLeaderboard> GetBlitzPriestDisciplineLeaderboard(string region);
    Task<PvpLeaderboard> GetBlitzPriestHolyLeaderboard(string region);
    Task<PvpLeaderboard> GetBlitzPriestShadowLeaderboard(string region);
    Task<PvpLeaderboard> GetBlitzRogueAssassinationLeaderboard(string region);
    Task<PvpLeaderboard> GetBlitzRogueOutlawLeaderboard(string region);
    Task<PvpLeaderboard> GetBlitzRogueSubtletyLeaderboard(string region);
    Task<PvpLeaderboard> GetBlitzShamanElementalLeaderboard(string region);
    Task<PvpLeaderboard> GetBlitzShamanEnhancementLeaderboard(string region);
    Task<PvpLeaderboard> GetBlitzShamanRestorationLeaderboard(string region);
    Task<PvpLeaderboard> GetBlitzWarlockAfflictionLeaderboard(string region);
    Task<PvpLeaderboard> GetBlitzWarlockDemonologyLeaderboard(string region);
    Task<PvpLeaderboard> GetBlitzWarlockDestructionLeaderboard(string region);
    Task<PvpLeaderboard> GetBlitzWarriorArmsLeaderboard(string region);
    Task<PvpLeaderboard> GetBlitzWarriorProtectionLeaderboard(string region);
    Task<PvpLeaderboard> Get3v3Leaderboard(string region, GameFlavor flavor = GameFlavor.MistsClassic);
    Task<PvpLeaderboard> Get2v2Leaderboard(string region, GameFlavor flavor = GameFlavor.MistsClassic);
    Task<PvpLeaderboard> Get5v5Leaderboard(string region, GameFlavor flavor = GameFlavor.MistsClassic);
    Task<PvpLeaderboard> GetRBGLeaderboard(string region, GameFlavor flavor = GameFlavor.MistsClassic);

    Task InsertCacheCharacter(string characterName, string server, string region, GameFlavor flavor = GameFlavor.MistsClassic);
    Task InsertCacheClassCharacter(string bracket, PvpLeaderboardEntry player, CharacterProfileSummary summary, string region, GameFlavor flavor = GameFlavor.MistsClassic);
    Task ClearAllCachedClassCharacters(string bracket, string region, GameFlavor flavor = GameFlavor.MistsClassic);
    Task<List<string>> CachedCharacters(GameFlavor flavor = GameFlavor.MistsClassic);
    Task<List<PvpLeaderboardEntry?>> CachedClassCharacters(string region, string characterClass, string bracket, GameFlavor flavor = GameFlavor.MistsClassic);
    Task<IEnumerable<PvpLeaderboardAndTime?>> GetLadderHistory(string key, string region, GameFlavor flavor = GameFlavor.MistsClassic);
    Task InsertToPlayerPageActivity(string bracket, string region, PvpLeaderboardEntry player, GameFlavor flavor = GameFlavor.MistsClassic);
    Task<IEnumerable<PvpLeaderboardEntryandTime?>> GetPlayerPageActivity(string bracket, string region, string characterId, GameFlavor flavor = GameFlavor.MistsClassic);
    Task BracketPlayerExpiration(string bracket, string region, GameFlavor flavor = GameFlavor.MistsClassic);
    Task InsertToBracketActivityPage(string bracket, string region, PvpLeaderboardEntry oldPlayer, PvpLeaderboardEntry newPlayer, GameFlavor flavor = GameFlavor.MistsClassic);
    Task<IEnumerable<PlayerActivity?>> GetBracketActivityPage(string bracket, string region, GameFlavor flavor = GameFlavor.MistsClassic);
    Task<CharacterProfileSummary> GetCharSummary(string server, string characterName, string region, GameFlavor flavor = GameFlavor.MistsClassic);
    Task<PvpRewardsIndex> GetPvPRewards(string region, GameFlavor flavor = GameFlavor.MistsClassic);
    Task<CharacterAppearanceSummary> GetCharAppearance(string server, string characterName, string region, GameFlavor flavor = GameFlavor.MistsClassic);
    Task<CharacterEquipmentSummary> GetCharEquipment(string server, string characterName, string region, GameFlavor flavor = GameFlavor.MistsClassic);
    Task<bool> ClearCharacterCache(string server, string characterName, string region, GameFlavor flavor = GameFlavor.MistsClassic);
    Task<PlayableClass?> GetPlayableClass(int classId, string region, GameFlavor flavor = GameFlavor.Retail);
    Task<CharacterPvpBracketStatistics> GetPvpBracketRating(string server, string characterName, string pvpBracket, string region, GameFlavor flavor = GameFlavor.MistsClassic);
    Task<CharacterStatisticsSummary> GetCharacterStats(string server, string characterName, string region, GameFlavor flavor = GameFlavor.MistsClassic);
    Task<CharacterAchievementsSummary> GetCharacterAchievements(string server, string characterName, string region, GameFlavor flavor = GameFlavor.MistsClassic);
    Task ClearLeaderboard(string bracket, string region, GameFlavor flavor = GameFlavor.MistsClassic);
    Task<IEnumerable<PlayerActivity?>> GetBracketClassFilteredActivityPage(string bracket, string region, string characterClass, GameFlavor flavor = GameFlavor.MistsClassic);
    Task<string> GetCharacterSpecName(string server, string characterName, string region, GameFlavor flavor = GameFlavor.MistsClassic);
    WarcraftClient? overrideClient{get; set;}
    //namespace builders, exposed so callers can reproduce a cached key exactly
    string GetProfileRegion(string region, GameFlavor flavor = GameFlavor.MistsClassic);
    string GetDynamicRegion(string region, GameFlavor flavor = GameFlavor.MistsClassic);
    string GetStaticRegion(string region, GameFlavor flavor = GameFlavor.MistsClassic);
    Task<ItemDisplayInfo?> GetItemDisplayInfo(int itemId, string region, GameFlavor flavor);
    Task<ItemMedia?> GetItemIcon(int itemId, string region, GameFlavor flavor = GameFlavor.MistsClassic);
    Task<CharacterSpecializationsSummary> GetPlayerTalents(string server, string characterName, string region, GameFlavor flavor = GameFlavor.MistsClassic);
    Task<TalentTree?> GetTalentTree(int specId, string region, GameFlavor flavor = GameFlavor.Retail);
    Task InsertActivityCacheClassCharacter(string bracket, PvpLeaderboardEntry oldPlayer, PvpLeaderboardEntry newPlayer, CharacterProfileSummary characterClass, string region, GameFlavor flavor = GameFlavor.MistsClassic);
    Task BracketClassPlayerExpiration(string bracket, string region, string characterClass, GameFlavor flavor = GameFlavor.MistsClassic);
    Task<int> GetSeason(string region, GameFlavor flavor = GameFlavor.MistsClassic);
    Task<DateTimeOffset?> GetSeasonStart(string region, GameFlavor flavor = GameFlavor.MistsClassic);
    Task SavePvpCharacterSummary(PvpCharacterSummary newPvpCharacterSummary, string bracket, string region, GameFlavor flavor = GameFlavor.MistsClassic);
    Task<List<PvpCharacterSummary?>> GetPvpLeaderSummaries(string bracket, string region, GameFlavor flavor = GameFlavor.MistsClassic);
    Task ClearPvpCharacterSummary(string bracket, string region, GameFlavor flavor = GameFlavor.MistsClassic);
    Task InsertAltList(string server, string characterName, string region, CharacterAchievementsSummary achievements, GameFlavor flavor = GameFlavor.MistsClassic);
    Task IndexAltList(string server, string characterName, string region, GameFlavor flavor = GameFlavor.MistsClassic);
    Task<List<string>> GetAlts(string server, string characterName, string region, GameFlavor flavor = GameFlavor.MistsClassic);
    Task<RealmsIndex?> GetRealms(string region, GameFlavor flavor = GameFlavor.MistsClassic);
}
