<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Description>The Argent Pony .NET client for the Blizzard World of Warcraft Game Data and Profile APIs</Description>
    <Title>Argent Pony Warcraft Client</Title>
    <PackageTags>Warcraft;World-of-Warcraft;WoW;Blizzard</PackageTags>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageIcon>ArgentPony.png</PackageIcon>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <PropertyGroup Condition="'$(CI)' == 'true'">
    <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
  </PropertyGroup>

  <ItemGroup>
    <Using Include="System.Text.Json" />
    <Using Include="System.Text.Json.Serialization" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.12" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.12" />
    <PackageReference Include="System.Threading.RateLimiting" Version="10.0.12" />
  </ItemGroup>

  <ItemGroup>
    <None Include="docs/ArgentPony.png" Pack="true" PackagePath="\" />
    <None Include="docs/README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

</Project>